name: vishal-workflow
on: 
  workflow_dispatch:
  
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "Hello world"
      - name: goodBy
        run: echo "done bye"
